consumer:
    ip: 127.0.0.1
producer:
    ip: 172.23.239.127
    port: 9092
#server:
#    port: 8433
spring:
    data:
        mongodb:
            database: mydatabase
            port: 27017
            uri: mongodb://127.0.0.1/mydatabase
