management:
  security:
    enabled: false
spring:
  application:
    name: user-registration-service
#  data:
#    mongodb:
#      database: userDetails
#      uri: mongodb://127.0.0.1/userDetails 
  data:
  mongodb:
    uri: mongodb://127.0.0.1/userDetails
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka/
    register-with-eureka: true
    fetch-registry: true
