spring:
    application:
        name: zuulgateway
ribbon:
    eureka:
        enabled: false
zuul:
    routes:
        input-kafka:
            url: http://localhost:8148
        input-lemmatize:
            url: http://localhost:8140
        input-postag:
            url: http://localhost:8142
        input-tagger:
            url: http://localhost:8144
        user-registration-service:
            url: http://localhost:8182
    # host:
    #     socket-timeout-millis: 30000
eureka:         #tells about the Eureka server details and its refresh time
   client:
       serviceUrl:
           defaultZone: http://localhost:8066/eureka/
       register-with-eureka: true
       fetch-registry: true
    instance:
      hostname: localhost
      leaseRenewalIntervalInSeconds: 10
management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
#tells about the Eureka server details and its refresh time
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8066/eureka/
#     register-with-eureka: true
#     fetch-registry: true